name: Container Security Scan

on:
  workflow_call:
    inputs:
      image:
        description: container image
        required: true
        type: string
      artifact:
        description: github artifact
        required: false
        type: string

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
      - uses: step-security/harden-runner@aa817ef3512b39bbe179e1c24cc63b4a421ab219 # v2.4.1
        with:
          egress-policy: audit
      - uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        if: ${{ inputs.artifact != '' }}
        with:
          name: ${{ inputs.artifact }}
          path: /tmp
      - run: |
          docker load --input /tmp/${{ inputs.artifact }}.tar
        if: ${{ inputs.artifact != '' }}
      - uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          image: ${{ inputs.image }}
          artifact-name: image.spdx.json
          dependency-snapshot: true
      - id: grype
        uses: anchore/scan-action@f8d9cf1352c872bf9c61e87c1d02a7d1c63ef0b9 # v3.3.6
        with:
          image: ${{ inputs.image }}
          fail-build: false
          severity-cutoff: critical
      - uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v2
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype
      - uses: aquasecurity/trivy-action@3dd517d8c9544cb8bfc2762d222b8e327bad2b75 # 0.11.2
        with:
          image-ref: ${{ inputs.image }}
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v2
        with:
          sarif_file: trivy-results.sarif
          category: trivy
