name: Container Security Scan

on:
  workflow_call:
    inputs:
      image:
        description: container image
        required: true
        type: string
      artifact:
        description: github artifact
        required: false
        type: string

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        if: ${{ inputs.artifact != '' }}
        with:
          name: ${{ inputs.artifact }}
          path: /tmp
      - run: |
          docker load --input /tmp/${{ inputs.artifact }}.tar
        if: ${{ inputs.artifact != '' }}
      - uses: anchore/sbom-action@ace0b9722a703812d78949ee4ac5b90de1c0eba2
        with:
          image: ${{ inputs.image }}
          artifact-name: image.spdx.json
          dependency-snapshot: true
      - id: grype
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a # v3.6.4
        with:
          image: ${{ inputs.image }}
          fail-build: false
          severity-cutoff: critical
      - uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v2
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype
      - uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca # 0.16.1
        with:
          image-ref: ${{ inputs.image }}
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v2
        with:
          sarif_file: trivy-results.sarif
          category: trivy
