name: Events

on:
  pull_request: {}
  push: {}
  
jobs:
  events:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - run: |
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "EVENT: ${{ toJSON(github.event) }}"
          echo "EVENT_FILE: $(cat $GITHUB_EVENT_PATH}"
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: events.${{ github.event_name }}.json
          path: ${{ env.GITHUB_EVENT_PATH }}
