name: Merge

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  scorecard:
    uses: ./.github/workflows/openssf-scorecard.yaml

    permissions:
      contents: read
      security-events: write
      id-token: write

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:
      releases_created: ${{ steps.release_please.outputs.releases_created }}
      outputs: ${{ toJSON(steps.release_please.outputs) }}

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - id: release_please
        uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        with:
          command: manifest
          monorepo-tags: true

  container_releases_matrix:
    if: ${{ needs.release.outputs.releases_created }}
    runs-on: ubuntu-latest

    needs:
      - release

    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
      releases: ${{ steps.releases.outputs.result }}

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        id: releases
        env:
          OUTPUTS: ${{ needs.release.outputs.outputs }}
        with:
          script: |
            const outputs=JSON.parse(process.env.OUTPUTS);

            var releases = {};

            let paths = JSON.parse(outputs.paths_released)

            paths.forEach(path => {
              if (path.startsWith('containers/')) {
                  var release = {};
                  Object.keys(outputs).filter(name => name.startsWith(`${path}--`)).forEach(key => {
                    release[key.replace(`${path}--`,'')]=outputs[key]
                  });
                }
                releases[path]=release
            });

            return releases
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        id: matrix
        env:
          RELEASES: ${{ steps.releases.outputs.result }}
        with:
          script: |
            const releases=JSON.parse(process.env.RELEASES);

            return Object.keys(releases).filter(name => releases[name].release_created == 'true')

  container_build_release:
    if: ${{needs.container_releases_matrix.outputs.matrix != '[]'}}
    needs:
      - container_releases_matrix

    permissions:
      contents: write
      packages: write
      security-events: write

    strategy:
      fail-fast: false

      matrix:
        path: ${{ fromJSON(needs.container_releases_matrix.outputs.matrix) }}

    uses: ./.github/workflows/container-build.yaml
    with:
      path: ${{ matrix.path }}
      release: ${{ toJson(fromJSON(needs.container_releases_matrix.outputs.releases)[matrix.path]) }}

  container_changes_matrix:
    if: ${{ !needs.release.outputs.releases_created }}
    runs-on: ubuntu-latest

    needs:
      - release

    outputs:
      matrix: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          sparse-checkout: |
            containers
          fetch-depth: 0
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        id: filters
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          result-encoding: string
          script: |
            const workspace = process.env.WORKSPACE
            const globber = await glob.create('containers/*/Dockerfile');

            String.prototype.format = function() {
              let formatted = this;
              for (let i = 0; i < arguments.length; i++) {
                let regexp = new RegExp('\\{'+i+'\\}', 'gi');
                formatted = formatted.replace(regexp, arguments[i]);
              }
              return formatted;
            };

            var output = "";
            for await (const file of globber.globGenerator()) {
              core.debug(`Found: ${file} => ${file.replace(`${workspace}/`,'')}`);
              var path = file.replace(`${workspace}/`,'').split('/').slice(0,-1).join('/');
              output += "{0}:\n  - '{0}/**'\n".format(path);
            }
            return output
      - uses: dorny/paths-filter@7267a8516b6f92bdb098633497bad573efdbf271 # v2.12.0
        id: changes
        with:
          filters: ${{ steps.filters.outputs.result }}

  container_build_change:
    if: ${{needs.container_changes_matrix.outputs.matrix != '[]'}}

    needs:
      - container_changes_matrix

    permissions:
      contents: write
      packages: write
      security-events: write

    strategy:
      fail-fast: false

      matrix:
        path: ${{ fromJSON(needs.container_changes_matrix.outputs.matrix) }}

    uses: ./.github/workflows/container-build.yaml
    with:
      path: ${{ matrix.path }}
