name: Nightly

on:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: {}

permissions: read-all

jobs:
  scorecard:
    uses: ./.github/workflows/openssf-scorecard.yaml
    permissions:
      contents: read
      security-events: write
      id-token: write

  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - id: get_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: trunk-io/trunk-action/upgrade@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          prefix: "deps(trunk-check):"

  codeql:
    uses: ./.github/workflows/codeql.yaml
    permissions:
      actions: read
      contents: read
      security-events: write

  containers:
    uses: ./.github/workflows/container-list.yaml
    permissions:
      contents: read
    with:
      changed: false

  container-security-scan:
    needs:
      - containers

    if: ${{ needs.containers.outputs.list != '[]' }}

    strategy:
      fail-fast: false

      matrix:
        container: ${{ fromJson(needs.containers.outputs.list) }}

    uses: ./.github/workflows/container-security-scan.yaml

    permissions:
      contents: write
      security-events: write

    with:
      image: ghcr.io/remkomolier/${{ matrix.container }}:edge

  housekeeping:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: Mattraks/delete-workflow-runs@708edabfaf5f9b6357ce4c375d22c83834c87f7d # v2.0.5
        with:
          retain_days: 30
          keep_minimum_runs: 6

  alpine-refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - id: get_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      - run: |
          cd containers/alpine
          docker build . -t alpine.local
          docker run alpine.local apk info -v | sort -u > packages.txt
          git diff
      - id: pull-request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: steps.get_token.outputs.token
          add-paths: |
            containers/alpine
          commit-message: "deps(containers/alpine): updated core dependencies"
          committer: Alpine Dependencies Bot <139859299+remkomolier-repo-jeeves[bot]@users.noreply.github.com>
          branch: dependencies/containers/alpine
          title: Alpine Core Packages Dependencies Update
      - if: ${{ steps.pull-request.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: steps.get_token.outputs.token
          pull-request-number: steps.pull-request.outputs.pull-request-number
          merge-method: rebase
