name: Pull Request Completed

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions: read-all

jobs:
  trunk-annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: trunk-io/trunk-action@782e83f803ca6e369f035d64c6ba2768174ba61b # v1.1.6
        with:
          post-annotations: true
