name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions: read-all

jobs:
  trunk-check:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: trunk-io/trunk-action@65228585e2c6128315f0f2d5190e2eae7f5c32c6 # v1.1.10
        with:
          save-annotations: true

  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/dependency-review-action@c74b580d73376b7750d3d2a50bfb8adc2c937507 # v3.1.5

  codeql:
    uses: ./.github/workflows/codeql.yaml

    permissions:
      actions: read
      contents: read
      security-events: write

  container_changes_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        id: filters
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          result-encoding: string
          script: |
            const workspace = process.env.WORKSPACE
            const globber = await glob.create('containers/*/Dockerfile');

            String.prototype.format = function() {
              let formatted = this;
              for (let i = 0; i < arguments.length; i++) {
                let regexp = new RegExp('\\{'+i+'\\}', 'gi');
                formatted = formatted.replace(regexp, arguments[i]);
              }
              return formatted;
            };

            var output = "";
            for await (const file of globber.globGenerator()) {
              core.debug(`Found: ${file} => ${file.replace(`${workspace}/`,'')}`);
              var path = file.replace(`${workspace}/`,'').split('/').slice(0,-1).join('/');
              output += "{0}:\n  - '{0}/**'\n".format(path);
            }
            return output
      - uses: dorny/paths-filter@7267a8516b6f92bdb098633497bad573efdbf271 # v2.12.0
        id: changes
        with:
          filters: ${{ steps.filters.outputs.result }}

  container_build_change:
    if: ${{needs.container_changes_matrix.outputs.matrix != '[]'}}

    needs:
      - codeql
      - container_changes_matrix

    permissions:
      contents: write
      packages: write
      security-events: write

    strategy:
      fail-fast: false

      matrix:
        path: ${{ fromJSON(needs.container_changes_matrix.outputs.matrix) }}

    uses: ./.github/workflows/container-build.yaml
    with:
      path: ${{ matrix.path }}

  dependabot:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - id: metadata
        uses: dependabot/fetch-metadata@c9c4182bf1b97f5224aee3906fd373f6b61b4526 # v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: ${{ steps.metadata.outputs.package-ecosystem == 'github_actions' && contains(fromJSON('["version-update:semver-minor","version-update:semver-patch"]'), steps.metadata.outputs.update-type) }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
