name: Renovate

on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      logLevel:
        type: string
        required: false
        default: info
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true
  push:
    branches:
      - main
    paths:
      - .github/renovate.json
  schedule:
    - cron: 59 0-6,22-23 * * *
    - cron: 4/5 7-21 * * *

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - id: get_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.get_token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_USERNAME: remkomolier-repo-jeeves[bot]
          RENOVATE_GIT_AUTHOR: Self-hosted Renovate Bot <139859299+remkomolier-repo-jeeves[bot]@users.noreply.github.com>
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_ASSIGN_AUTOMERGE: "true"
          RENOVATE_ASSIGNEES_FROM_CODE_OWNERS: "true"
          LOG_LEVEL: ${{ (inputs.logLevel != '') && inputs.logLevel || 'info' }}
