name: Trunk Cache

on:
  push:
    branches:
      - main
    paths:
      - .trunk/trunk.yaml

permissions: read-all

jobs:
  trunk-cache:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: trunk-io/trunk-action@86b68ffae610a05105e90b1f52ad8c549ef482c2 # v1.1.16
        with:
          check-mode: populate_cache_only
