name: Trunk Cache

on:
  push:
    branches:
      - main
    paths:
      - .trunk/trunk.yaml

permissions: read-all

jobs:
  trunk-cache:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: trunk-io/trunk-action@883e222ef19201ad402ef73e58101ec8186d7d54 # v1.1.7
        with:
          check-mode: populate_cache_only
