name: Trunk Cache

on:
  push:
    branches:
      - main
    paths:
      - .trunk/trunk.yaml

permissions: read-all

jobs:
  trunk-cache:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
        with:
          check-mode: populate_cache_only
